---
- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Extract file into directory
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Install npm
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Stop app
  become: yes
  command: pm2 stop default

- name: Start app
  become: yes
  command: pm2 start npm -- start
