---
# - name: Create directory
#   file:
#     path: ~/web
#     state: directory

- name: Extract file into directory
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: Executing node
  shell: |
    pm2 start npm -- start
