---
- name: Extract file into directory
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Install npm
  become: yes
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: Stop app
  shell: |
    pm2 stop default

- name: Start app
  shell: |
    pm2 start npm -- start
